import enum


class AuditEntityType(str, enum.Enum):
    COMPANY = "COMPANY"
    HIRING_OPPORTUNITY = "HIRING_OPPORTUNITY"
    APPLICATION = "APPLICATION"
    STUDENT_PROFILE = "STUDENT_PROFILE"
    SHORTLIST_IMPORT = "SHORTLIST_IMPORT"
    EXPORT = "EXPORT"
    USER = "USER"


class AuditAction(str, enum.Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    PUBLISH = "PUBLISH"
    ARCHIVE = "ARCHIVE"
    APPLY = "APPLY"
    WITHDRAW = "WITHDRAW"
    STATUS_CHANGED = "STATUS_CHANGED"
    EXPORT_GENERATED = "EXPORT_GENERATED"
    SHORTLIST_IMPORTED = "SHORTLIST_IMPORTED"
    VERIFY = "VERIFY"
    ROLE_ASSIGNED = "ROLE_ASSIGNED"
    ROLE_REMOVED = "ROLE_REMOVED"
