export const NAV_ITEMS = [
  {
    title: "Student",
    href: "/workspace/student",
    icon: "GraduationCap",
    roles: ["STUDENT", "SUPER_ADMIN"],
  },
  {
    title: "Opportunities",
    href: "/workspace/student/opportunities",
    icon: "Briefcase",
    roles: ["STUDENT", "SUPER_ADMIN"],
  },
  {
    title: "Convener",
    href: "/workspace/convener",
    icon: "Users",
    roles: ["PLACEMENT_CONVENER", "SUPER_ADMIN"],
  },
  {
    title: "Companies",
    href: "/workspace/convener/companies",
    icon: "Building2",
    roles: ["PLACEMENT_CONVENER", "PLACEMENT_CELL", "SUPER_ADMIN"],
  },
  {
    title: "Opportunity Ops",
    href: "/workspace/convener/opportunities",
    icon: "Briefcase",
    roles: ["PLACEMENT_CONVENER", "PLACEMENT_CELL", "SUPER_ADMIN"],
  },
  {
    title: "Placement Cell",
    href: "/workspace/placement-cell",
    icon: "Building2",
    roles: ["PLACEMENT_CELL", "SUPER_ADMIN"],
  },
  {
    title: "Admin",
    href: "/workspace/admin",
    icon: "Shield",
    roles: ["SUPER_ADMIN", "PLACEMENT_CELL"],
  },
  {
    title: "Users",
    href: "/workspace/admin/users",
    icon: "Users",
    roles: ["SUPER_ADMIN", "PLACEMENT_CELL"],
  },
  {
    title: "Departments",
    href: "/workspace/admin/departments",
    icon: "Building2",
    roles: ["SUPER_ADMIN", "PLACEMENT_CELL"],
  },
  {
    title: "Seasons",
    href: "/workspace/admin/seasons",
    icon: "Briefcase",
    roles: ["SUPER_ADMIN", "PLACEMENT_CELL"],
  },
  {
    title: "Settings",
    href: "/workspace/admin/settings",
    icon: "Settings",
    roles: ["SUPER_ADMIN"],
  },
  {
    title: "System Health",
    href: "/workspace/admin/system-health",
    icon: "Activity",
    roles: ["SUPER_ADMIN"],
  },
  {
    title: "Feature Flags",
    href: "/workspace/admin/feature-flags",
    icon: "ToggleLeft",
    roles: ["SUPER_ADMIN"],
  },
  {
    title: "Maintenance",
    href: "/workspace/admin/maintenance",
    icon: "Wrench",
    roles: ["SUPER_ADMIN"],
  },
] as const;
