import enum


class NotificationType(str, enum.Enum):
    OPPORTUNITY_PUBLISHED = "OPPORTUNITY_PUBLISHED"
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
    APPLICATION_WITHDRAWN = "APPLICATION_WITHDRAWN"
    APPLICATION_STATUS_CHANGED = "APPLICATION_STATUS_CHANGED"
    SHORTLISTED = "SHORTLISTED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    OFFER_RELEASED = "OFFER_RELEASED"


class DeliveryStatus(str, enum.Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class NotificationEntityType(str, enum.Enum):
    HIRING_OPPORTUNITY = "HIRING_OPPORTUNITY"
    APPLICATION = "APPLICATION"
    SHORTLIST_IMPORT = "SHORTLIST_IMPORT"
